### ISSUE TITLE
Pause Dimmer service in high ambient lights.

### ISSUE THREAD

**Issue by ahmadalibaloch** [code-crusher/Dimmer#1]
Add some shortcut key to turn off the dimmer or devise another solution. The time may be not affected in all cases :-)

**Comment by code-crusher** [comment]
@ahmadalibaloch You can turn on the notification so that you can pause, start or stop directly from there. :)

**Comment by ahmadalibaloch** [comment]
I can't see anything on the screen! its dark. How can I unlock and find the notification bar?? There could be 10 notifications from other apps too.

**Comment by code-crusher** [comment]
@ahmadalibaloch if you are stuck right now, you can restart your device. And for later i'll add a pop up to ask to continue for this service in the morning or when the ambient light is high. Thank you for reporting this use-case and your contributions are also welcome. 😄

**Comment by ahmadalibaloch** [comment]
Yes, this is a good solution and will be new in this app as compared to my [old app](https://play.google.com/store/apps/details?id=com.haxor&hl=en). Thank you

**Comment by code-crusher** [comment]
@ahmadalibaloch i have updated the app with the required changes. Please test and close the issue :)

**Comment by ahmadalibaloch** [comment]
After updating from PlayStore, I have tested indoor but it was not working. I turned the dimmer on full (dark). Faced the light in room but it was not disabling automatically. The time is also not between start and end time.

**Comment by code-crusher** [comment]
@ahmadalibaloch I have tested it many times, it is working just fine in every environment. What is your device?

**Comment by ahmadalibaloch** [comment]
Okay I brought the phone very near to the light bulb and it worked. I think you need to lower the amount of luminance to trigger the message or may be open it for us to change? :-) Phone is Galaxy S4 I9505

**Comment by code-crusher** [comment]
@ahmadalibaloch maybe then it depends on device to device. Let me make it adjustable by user :)

**Comment by ahmadalibaloch** [comment]
Thank you for this beautiful gift :-) closing the issue.

**Comment by code-crusher** [comment]
@ahmadalibaloch Welcome and thanks for your suggestions :). Will update soon.
